version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest
      - test-1.19
jobs:
  test-latest: &test-template
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/nbari/violetear
    steps:
      - checkout
      - run: make test
  test-1.19:
    <<: *test-template
    docker:
      - image: circleci/golang:1.19
