version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-latest
      - test-1.11
      - test-1.10
      - test-1.9
      - test-1.7
jobs:
  test-latest: &test-template
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/nbari/violetear
    steps:
      - checkout
      - run: make test
  test-1.11:
    <<: *test-template
    docker:
      - image: circleci/golang:1.11
  test-1.10:
    <<: *test-template
    docker:
      - image: circleci/golang:1.10
  test-1.9:
    <<: *test-template
    docker:
      - image: circleci/golang:1.9
  test-1.7:
    <<: *test-template
    docker:
      - image: circleci/golang:1.7
